# Configuración del datasource para SQL Server
spring:
  datasource:
    driver-class-name: 'org.postgresql.Driver'
    url: 'jdbc:postgresql://dpg-cs3e9qg8fa8c73d51qg0-a.oregon-postgres.render.com/plataforma_eventos'
    username: 'plataforma_eventos_user'
    password: 'lVyX3uh0XCXnFhKAGriKDxLSy3onpDH7'

# Configuración de Hibernate
  jpa:
    hibernate:
      dialect: 'org.hibernate.dialect.PostgreSQLDialect'
      ddl-auto: update
    show-sql: true

